### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by guy426** [lmdpua/CP2112_SH366000_Flasher#1]
I get this error with visual studio 2019 and qt 5.15.2:
.\mainwindow.cpp(516): error C2131: expression did not evaluate to a constant
.\mainwindow.cpp(516): note: failure was caused by a read of a variable outside its lifetime
.\mainwindow.cpp(516): note: see usage of 'str_len'
.\mainwindow.cpp(520): error C3863: array type 'QChar [str_len]' is not assignable

**Comment by lmdpua** [comment]
I can't find this place. It's here?
![image](https://user-images.githubusercontent.com/17345244/169413838-f48bd65e-f7b6-492b-92ee-2f4786f9d6ea.png)

I had issues at this point with the MSVC compiler, but MinGW handled it. But I still redid a piece of code here

**Comment by guy426** [comment]
I have try to compile old sources...
with latest code error is:
.\mainwindow.cpp(531): error C2665: 'QString::fromLocal8Bit': none of the 2 overloads could convert
all the argument types
C:\Qt\5.15.2\msvc2019_64\include\QtCore/qstring.h(708): note: could be 'QString QString::fromLocal8B
it(const char *,int)'
.\mainwindow.cpp(531): note: while trying to match the argument list '(QByteRef *, qsizetype)'

**Comment by lmdpua** [comment]
First.  Please download the latest version of the source code.  The very first version contains some bugs.  I'm not saying that the latest version is sinless, but still.  Second.  Also try the mingw compiler, I had less problems with it.  Third. And also you can generally remove a piece of code from which the problem.  Fourth.  Update QT to the latest version.
Perhaps some features do not work in older versions.  And finally, download the finished release.  Make sure it works for you.  This will encourage you not to quit what you started.

**Comment by guy426** [comment]
Release don't work in my PC cause windows 7.
Which versions of mingw are you using ?

**Comment by lmdpua** [comment]
Win 10 Pro 21H1 19043.1706
QT 6.2.2 MinGW 64-bit
MinGW 9.0.0 64-bit for C++

**Comment by lmdpua** [comment]
![image](https://user-images.githubusercontent.com/17345244/169770853-33743743-a762-451e-be9c-08d790a1e74e.png)

**Comment by lmdpua** [comment]
> I have try to compile old sources...
> with latest code error is:
> .\mainwindow.cpp(531): error C2665: 'QString::fromLocal8Bit': none of the 2 overloads could convert
> all the argument types
> C:\Qt\5.15.2\msvc2019_64\include\QtCore/qstring.h(708): note: could be 'QString QString::fromLocal8B
> it(const char *,int)'
> .\mainwindow.cpp(531): note: while trying to match the argument list '(QByteRef *, qsizetype)'

try changing the variable str_len type from qsizetype to int
In the fifth version of qt, there should be an int, and in the sixth there is already a qsizetype

**Comment by guy426** [comment]
I think that my qt5 qstring.h cause the error:
candidate function not viable: no known conversion from 'QByteRef *' to 'const char *' for 1st argument
I can't compile also with mingw, same problem.
It's the only error that i get.

**Comment by lmdpua** [comment]
Try this
str = QString::fromLocal8Bit((char*)&flashData[str_start], str_len);
If it doesn't work, I'll think about how else you can convert the data to a string

**Comment by lmdpua** [comment]
Here is another way

![image](https://user-images.githubusercontent.com/17345244/169895525-2a6a1d92-1d6a-4a5f-858a-69cbc71542a2.png)

**Comment by lmdpua** [comment]
We copy the data from the flashData array to a standard array byte by byte, add '\0' at the end. (We make the end of the line in this way).  And then convert it to a QString (fromStdString)

**Comment by guy426** [comment]
With line 532 modify as "str = QString::fromLocal8Bit((char*)&flashData[str_start], str_len);"
code compile with qt 5.15.2 but program hangs immediately without any error.
Can you build release version without DX12 ?

**Comment by guy426** [comment]
I have make some progress...
Code compile with -fpermissive flags add to project.
Program crashes because it cannot find the cp2112 libraries. if i manually copy the dll it run!

**Comment by lmdpua** [comment]
Oh, that's great! Yes, you need to add a library. I couldn't figure out how to do it for a long time.

**Comment by lmdpua** [comment]
By the way, what version are you building for? 32 or 64 bits? There are different library files

**Comment by doctorman** [comment]
can you add a compiled version ready to run on windows for less savvy people. 

so I can use this software  with CP2112  to analyze and flash batteries?
is this better than your own flasher?
